# Generated by Django 3.2.9 on 2021-11-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabGiratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso1', models.FloatField()),
                ('peso2', models.FloatField()),
                ('peso3', models.FloatField()),
                ('peso4', models.FloatField()),
                ('peso5', models.FloatField()),
                ('peso6', models.FloatField()),
                ('peso7', models.FloatField()),
                ('peso8', models.FloatField()),
                ('peso9', models.FloatField()),
                ('peso10', models.FloatField()),
                ('peso11', models.FloatField()),
                ('peso12', models.FloatField()),
                ('peso13', models.FloatField()),
                ('peso14', models.FloatField()),
                ('peso15', models.FloatField()),
                ('peso16', models.FloatField()),
                ('peso17', models.FloatField()),
                ('peso18', models.FloatField()),
                ('peso19', models.FloatField()),
                ('crated', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
