# Generated by Django 3.2.9 on 2021-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wi', models.FloatField(max_length=5)),
                ('p80', models.FloatField(max_length=6)),
                ('f80', models.FloatField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['wi'],
            },
        ),
    ]
