# Generated by Django 3.2.9 on 2021-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLaboratorio', '0003_auto_20211109_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='f80',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='energia',
            name='p80',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='energia',
            name='wi',
            field=models.PositiveIntegerField(),
        ),
    ]
