# Generated by Django 3.2.9 on 2021-11-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLaboratorio', '0004_auto_20211109_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labgiratorio',
            name='peso18',
        ),
        migrations.RemoveField(
            model_name='labgiratorio',
            name='peso19',
        ),
    ]
