# Generated by Django 3.2.9 on 2021-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLaboratorio', '0005_auto_20211114_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura1', models.IntegerField()),
                ('abertura2', models.IntegerField()),
                ('abertura3', models.IntegerField()),
                ('abertura4', models.IntegerField()),
                ('abertura5', models.IntegerField()),
                ('abertura6', models.IntegerField()),
                ('abertura7', models.IntegerField()),
                ('abertura8', models.IntegerField()),
                ('abertura9', models.IntegerField()),
                ('abertura10', models.IntegerField()),
                ('abertura11', models.IntegerField()),
                ('abertura12', models.IntegerField()),
                ('abertura13', models.IntegerField()),
                ('abertura14', models.IntegerField()),
                ('abertura15', models.IntegerField()),
                ('abertura16', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='labgiratorio',
            old_name='crated',
            new_name='created',
        ),
    ]
