# Generated by Django 3.2.9 on 2021-11-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLaboratorio', '0007_labgiratorio_fechaactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labgiratorio',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='labgiratorio',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
