# Generated by Django 3.2.9 on 2021-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLaboratorio', '0008_auto_20211122_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='abertura',
            name='fechaActual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labgiratorio',
            name='fechaActual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
